import test from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {readFileSync,readdirSync,mkdtempSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {pathToFileURL} from "node:url";
import {build} from "esbuild";
import {newContent} from "../lib/candidate-workflow.ts";
import {queryStatus,queryStatusLabels,reviewProgress,screenerStatus,screenerStatusLabels} from "../lib/query-status.ts";
const db=new DatabaseSync(":memory:");
for(const file of readdirSync(new URL("../drizzle/",import.meta.url)).filter(f=>f.endsWith(".sql")&&!f.startsWith("0009")).sort())db.exec(readFileSync(new URL("../drizzle/"+file,import.meta.url),"utf8"));
const content=JSON.stringify(newContent("Сохранённый анализ"));
const insert=db.prepare("INSERT INTO candidates(id,context_key,subject,query,query_key,period,status,analysis_passed,revision,content_json,history_json,updated_by,updated_at) VALUES(?,'month:2026-10','Ёлки',?,?,'2026-10',?,0,1,?,'[]','manager@test',?)");
for(const [query,status,at] of [["a","rejected","2026-09-01"],["b","analysis","2026-09-15"],["c","deferred","2026-09-01"],["d","rejected","2026-09-01"]])insert.run(query,query,query,status,content,at);
const mark=db.prepare("INSERT INTO screener_marks(context_key,query_key,query,subject,status,updated_by,updated_at) VALUES('month:2026-10',?,?,'Ёлки',?,'owner@test',?)");
mark.run("a","a","shortlisted","2026-09-10");mark.run("b","b","excluded","2026-09-02");
db.exec(readFileSync(new URL("../drizzle/0009_unified_query_screening.sql",import.meta.url),"utf8"));
db.exec("PRAGMA recursive_triggers=ON");
globalThis.__queryDb={prepare(sql){let values=[];const q={bind(...v){values=v;return q;},async run(){return db.prepare(sql).run(...values);},async all(){return {results:db.prepare(sql).all(...values)};}};return q;},async batch(statements){db.exec("BEGIN");try{for(const s of statements)await s.run();db.exec("COMMIT");}catch(e){db.exec("ROLLBACK");throw e;}}};
const dir=mkdtempSync(join(tmpdir(),"query-screening-"));
await build({entryPoints:[new URL("../app/api/screener-marks/route.ts",import.meta.url).pathname],outfile:join(dir,"route.mjs"),bundle:true,platform:"node",format:"esm",logLevel:"silent",plugins:[{name:"db",setup(b){b.onResolve({filter:/^@\/db$/},()=>({path:"db",namespace:"fake"}));b.onLoad({filter:/.*/,namespace:"fake"},()=>({contents:"export const getRawDb=()=>globalThis.__queryDb",loader:"js"}));}}]});
const api=await import(pathToFileURL(join(dir,"route.mjs")).href);
const write=data=>api.POST(new Request("https://app.test/api/screener-marks",{method:"POST",headers:{"oai-authenticated-user-email":"owner@test"},body:JSON.stringify(data)}));
test("legacy decisions reconcile by date, deferred stays shortlisted, repeated sync preserves content and revision",async()=>{
 const payload={contextKey:"month:2026-10",action:"reconcile"};
 assert.equal((await write(payload)).status,200);
 const rows=()=>db.prepare("SELECT query_key,status,revision,content_json FROM candidates ORDER BY id").all();
 const before=rows();assert.deepEqual(before.map(r=>r.status),["analysis","analysis","deferred","rejected"]);
 assert.ok(before.every(r=>r.content_json===content));
 assert.deepEqual(db.prepare("SELECT status FROM screener_marks ORDER BY query_key").all().map(r=>r.status),["shortlisted","shortlisted","shortlisted","excluded"]);
 await write(payload);assert.deepEqual(rows(),before);
 await write({contextKey:"month:2026-10",status:"excluded",rows:[{query:"b",subject:"Ёлки"}]});
 assert.equal(rows()[1].status,"rejected");assert.equal(rows()[1].revision,2);
 await write({contextKey:"month:2026-10",status:"shortlisted",rows:[{query:"b",subject:"Ёлки"}]});
 assert.equal(rows()[1].status,"analysis");assert.equal(rows()[1].revision,3);
 await write({contextKey:"month:2027-10",status:"excluded",rows:[{query:"b",subject:"Ёлки"}]});
 assert.equal(rows()[1].status,"analysis","another launch month is independent");
});
test("screener exposes only three manual statuses while workflow progress remains derived",()=>{
 assert.deepEqual(Object.keys(screenerStatusLabels),["unreviewed","shortlisted","excluded"]);
 assert.equal(screenerStatus(),"unreviewed");assert.equal(screenerStatus("shortlisted"),"shortlisted");assert.equal(screenerStatus("excluded"),"excluded");
 assert.equal(Object.keys(queryStatusLabels).length,5,"internal workflow can keep richer outcomes without exposing them as screener statuses");
 assert.equal(queryStatus(),"unreviewed");assert.equal(queryStatus({status:"analysis_ready"}),"shortlisted");
 assert.equal(queryStatus(undefined,false,true),"shortlisted");
 assert.equal(queryStatus({status:"unreviewed"},false,true),"unreviewed");
 for(const status of ["sourcing","ready","purchased"])assert.equal(queryStatus({status}),"candidate");
 assert.equal(queryStatus({status:"deferred"}),"deferred");assert.equal(queryStatus({status:"rejected"}),"excluded");assert.equal(queryStatus(undefined,true),"excluded");
 assert.deepEqual(reviewProgress({status:"analysis"},true),{selected:true,manager:"active",owner:"waiting",outcome:null});
 assert.deepEqual(reviewProgress({status:"analysis_ready"},true),{selected:true,manager:"done",owner:"active",outcome:null});
 assert.equal(reviewProgress({status:"sourcing"},true).outcome,"candidate");
 assert.equal(reviewProgress({status:"deferred"},true).outcome,"deferred");
});
test("unreviewed is a durable screener state and reconcile does not re-shortlist it",async()=>{
 const before=db.prepare("SELECT revision,content_json FROM candidates WHERE id='b'").get();
 const response=await write({contextKey:"month:2026-10",status:"unmarked",rows:[{query:"b",subject:"Ёлки"}]});assert.equal(response.status,200);
 const after=db.prepare("SELECT status,analysis_passed,revision,content_json FROM candidates WHERE id='b'").get();
 assert.equal(after.status,"unreviewed");assert.equal(after.analysis_passed,0);assert.equal(after.revision,before.revision+1);assert.equal(after.content_json,before.content_json);
 assert.equal(db.prepare("SELECT status FROM screener_marks WHERE context_key='month:2026-10' AND query_key='b'").get(),undefined);
 await write({contextKey:"month:2026-10",action:"reconcile"});
 assert.equal(db.prepare("SELECT status FROM screener_marks WHERE context_key='month:2026-10' AND query_key='b'").get(),undefined);
});

test("bulk shortlist restores an explicitly unreviewed query without losing its analysis",async()=>{
 db.prepare("UPDATE candidates SET status='unreviewed' WHERE id='b'").run();
 const before=db.prepare("SELECT revision,content_json FROM candidates WHERE id='b'").get();
 const response=await write({contextKey:"month:2026-10",status:"shortlisted",rows:[{query:"b",subject:"Ёлки"}]});
 assert.equal(response.status,200);
 const after=db.prepare("SELECT status,revision,content_json FROM candidates WHERE id='b'").get();
 assert.equal(after.status,"analysis");assert.equal(after.revision,before.revision+1);assert.equal(after.content_json,before.content_json);
});
