"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Status={connected:boolean;revision:number;canEdit:boolean;storageReady:boolean;checkedAt:string|null;tariffsAt:string|null;error:string};
export function ApiConnections(){
  const [status,setStatus]=useState<Status|null>(null),[token,setToken]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function load(){try{const r=await fetch("/api/connections");const data=await r.json() as Status;if(!r.ok)throw new Error(data.error);setStatus(data);}catch{setMessage("Не удалось загрузить подключения. Попробуйте обновить.");}}
  useEffect(()=>{void load();},[]);
  async function act(action:"save"|"refresh"|"disconnect"){
    if(!status)return;if(action==="disconnect"&&!window.confirm("Отключить WB? Сохранённые расчёты останутся, обновление тарифов остановится."))return;
    setBusy(true);setMessage("");try{const r=await fetch("/api/connections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,revision:status.revision,...(action==="save"?{token}: {})})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setToken("");setMessage(action==="disconnect"?"WB отключён. Расчёты сохранены.":"Подключение проверено. Комиссии и тарифы складов получены.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Не удалось выполнить действие");}finally{setBusy(false);}
  }
  return <section className="max-w-3xl rounded-2xl border bg-white p-6"><div className="mb-6 border-b pb-5"><a href="/search-demand" className="font-semibold underline">MPStats — история спроса</a><p className="mt-1 text-sm text-muted-foreground">График, пики и рост поискового запроса. Здесь можно подключить API.</p><a href="/mpstats-check" className="mt-2 inline-block text-sm underline">Диагностика подключения</a></div><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Wildberries</h2><span className="text-sm text-muted-foreground">{status?.connected?"Ключ сохранён":"Не подключён"}</span></div><p className="mb-4 text-sm text-muted-foreground">Общее подключение для всех месяцев и разделов. Сейчас используется для комиссий по предметам и тарифов логистики.</p>{status?.canEdit&&<><label className="block text-sm font-medium" htmlFor="wb-api-key">{status.connected?"Заменить API-ключ":"API-ключ WB"}</label><Input id="wb-api-key" type="password" autoComplete="new-password" spellCheck={false} value={token} onChange={e=>setToken(e.target.value)} disabled={busy||!status.storageReady} placeholder="Вставьте ключ из кабинета WB" className="my-2"/><p className="mb-4 text-xs text-muted-foreground">Используйте ключ только для чтения с доступом к тарифам. Ключ хранится зашифрованным и после сохранения не отображается.</p><div className="flex flex-wrap gap-2"><Button disabled={busy||!token.trim()||!status.storageReady} onClick={()=>void act("save")}>{busy?"Проверяю…":"Проверить и сохранить"}</Button>{status.connected&&<><Button variant="outline" disabled={busy} onClick={()=>void act("refresh")}>Обновить тарифы</Button><Button variant="ghost" disabled={busy} onClick={()=>void act("disconnect")}>Отключить</Button></>}</div></>}{status&&!status.canEdit&&<p className="text-sm">Ключами управляет владелец.</p>}{status?.tariffsAt&&<p className="mt-4 text-sm text-muted-foreground">Тарифы получены: {new Date(status.tariffsAt).toLocaleString("ru-RU")}</p>}<p role="status" className="mt-4 text-sm">{message||status?.error||(!status?"Загружаем настройки…":"")}</p>{!status&&<Button variant="outline" onClick={()=>void load()}>Обновить</Button>}</section>;
}
