"use client";
import { useEffect, useState } from "react";
import { Truck, Package } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { Choice, NumberField, TextField } from "./candidate-workspace";
import { newModel } from "@/lib/candidate-workflow";
import { initialCalculatorSettings, minimumTaxHint, type CalculatorSettings, type SettingsRecord } from "@/lib/calculator-settings";

export function useCalculatorSettings() {
  const [record,setRecord]=useState<SettingsRecord|null>(null), [loading,setLoading]=useState(true), [error,setError]=useState("");
  useEffect(()=>{const abort=new AbortController();fetch("/api/calculator-settings",{signal:abort.signal}).then(async r=>{const data=await r.json() as SettingsRecord & {error?:string};if(!r.ok)throw new Error(data.error || "Не удалось загрузить настройки");setRecord(data);}).catch(e=>{if(!abort.signal.aborted)setError(e.message||"Не удалось загрузить настройки");}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[]);
  return {record,setRecord,loading,error};
}
export function CalculatorSettingsDialog({section,record,onSaved,canEdit}:{section:"import"|"wb";record:SettingsRecord|null;onSaved:(s:SettingsRecord)=>void;canEdit:boolean}) {
  const [open,setOpen]=useState(false),[draft,setDraft]=useState<CalculatorSettings>(record?.settings??initialCalculatorSettings()),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const ni=(key:keyof CalculatorSettings["import"],label:string)=><NumberField key={key} label={label} value={draft.import[key] as number|null} onChange={v=>setDraft({...draft,import:{...draft.import,[key]:v,...(key==="cnyPurchase"?{cnyCustoms:v}:key==="usdPurchase"?{usdCustoms:v}:{})}})}/>;
  const nw=(key:keyof CalculatorSettings["wb"],label:string)=><NumberField key={key} label={label} value={draft.wb[key] as number|null} onChange={v=>setDraft({...draft,wb:{...draft.wb,[key]:v}})}/>;
  async function save(){if(!record)return;setBusy(true);setError("");try{const r=await fetch("/api/calculator-settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({settings:{...record.settings,[section]:draft[section],...(section==="wb"?{wbProfiles:{...draft.wbProfiles,[draft.wb.scheme]:draft.wb}}:{})},revision:record.revision})});const data=await r.json() as SettingsRecord & {error?:string};if(!r.ok)throw new Error(data.error || "Не удалось сохранить настройки");onSaved(data);setOpen(false);}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить");}finally{setBusy(false);}}
  const china=section==="import";
  return <Dialog open={open} onOpenChange={value=>{if(busy)return;if(value){setDraft(record?.settings??initialCalculatorSettings());setError("");}setOpen(value);}}>
    <DialogTrigger asChild><Button variant="outline" className={china?"min-h-11 border-[#b9c9a9] bg-[#edf5e3] text-[#304a24]":"min-h-11 border-[#b9cbd6] bg-[#edf4f8] text-[#294755]"} disabled={!record}>{china?<Truck className="size-4"/>:<Package className="size-4"/>}{china?"Дефолты: Китай":"Дефолты: WB"}</Button></DialogTrigger>
    <DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{china?"Дефолты доставки из Китая":"Дефолты логистики и расходов WB"}</DialogTitle><DialogDescription>Новая модель сразу получает эти значения. В карточке их можно менять отдельно. Сохранённые модели не перезаписываются.</DialogDescription></DialogHeader>
      <fieldset disabled={!canEdit||busy} className="min-w-0 space-y-5">
        {china?<>
          <section><h3 className="mb-3 font-semibold">Курсы и платежи</h3><div className="grid gap-4 sm:grid-cols-3">{ni("cnyPurchase","Юань, ₽")}{ni("usdPurchase","USD, ₽")}{ni("dutyPct","Пошлина, %")}{ni("vatPct","Импортный НДС, %")}{ni("agentPct","Агент, %")}{ni("currencyControlPct","Валютный контроль, %")}</div><p className="mt-3 text-sm text-muted-foreground">Единые курсы для покупки и таможни. Импортный НДС включён в себестоимость. Пошлину проверьте по товару.</p></section>
          <section className="border-t pt-4"><h3 className="mb-3 font-semibold">Доставка</h3><div className="grid gap-4 sm:grid-cols-3"><Choice label="Способ доставки" value={draft.import.mode} options={[["groupage","Авто · сборный груз"],["container","Контейнер"]]} onChange={mode=>setDraft({...draft,import:{...draft.import,mode:mode as "groupage"|"container"}})}/>{ni("borderPct","Фрахт до границы, %")}{draft.import.mode==="groupage"?<>{ni("rateUsdM3","Тариф, $ / м³")}{ni("operationUsd","Операционный сбор, $")}{ni("densityKgM3","Тарифная плотность, кг/м³")}</>:<>{ni("containerUsd","Контейнер, $")}{ni("containerM3","Полезный объём, м³")}{ni("containers","Контейнеров")}</>}</div></section>
          <section className="border-t pt-4"><h3 className="mb-3 font-semibold">Расходы на партию, ₽</h3><div className="grid gap-4 sm:grid-cols-3">{ni("broker","Таможенное оформление")}{ni("terminal","Терминал")}{ni("inland","Вывоз груза")}{ni("unloading","Разгрузка")}{ni("inspection","Инспекция")}{ni("certification","Сертификация")}{ni("other","Прочее")}{ni("customsFeeOverride","Таможенный сбор вручную")}</div></section>
        </>:<>
          <section><h3 className="mb-3 font-semibold">Продажи и логистика</h3><div className="grid gap-4 sm:grid-cols-3"><Choice label="Схема продаж" value={draft.wb.scheme} options={[["FBW","FBW / FBO"],["FBS","FBS"]]} onChange={value=>{const scheme=value as "FBW"|"FBS";setDraft({...draft,wbProfiles:{...draft.wbProfiles,[draft.wb.scheme]:draft.wb},wb:{...(draft.wbProfiles[scheme]??initialCalculatorSettings().wb),scheme}});}}/>{nw("commissionPct","Комиссия WB, %")}{nw("extraCommissionPct","Допы к комиссии, %")}{nw("acquiringPct","Эквайринг, %")}{nw("buyoutPct","Выкуп, %")}{nw("forwardLogistics","Прямая / заказ, ₽")}{nw("returnLogistics","Обратная / невыкуп, ₽")}{nw("storage","Хранение / выкуп, ₽")}{nw("packaging","Упаковка / штука, ₽")}{nw("other","Прочие / выкуп, ₽")}{nw("drrPct","ДРР, %")}{nw("sppPct","СПП, %")}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><TextField type="date" label="Тарифы проверены на дату" value={draft.wb.tariffDate} onChange={tariffDate=>setDraft({...draft,wb:{...draft.wb,tariffDate}})}/><TextField label="Источник / склад / условия" value={draft.wb.tariffSource} onChange={tariffSource=>setDraft({...draft,wb:{...draft.wb,tariffSource}})}/></div><p className="mt-3 text-sm text-muted-foreground">Каждая схема хранит собственные значения. При переключении введённые настройки сохраняются. Комиссию и логистику конкретной модели проверьте по предмету, складу и габаритам.</p></section>
          <section className="border-t pt-4"><h3 className="mb-3 font-semibold">Налоги</h3><div className="grid gap-4 sm:grid-cols-3"><Choice label="Объект УСН" value={draft.wb.taxMode} options={[["profit","Доходы минус расходы"],["income","Доходы"]]} onChange={taxMode=>setDraft({...draft,wb:{...draft.wb,taxMode:taxMode as "profit"|"income"}})}/>{nw("taxPct","УСН, %")}{nw("vatPct","НДС с продажи, %")}</div>{draft.wb.taxMode==="profit"&&<><label className="mt-4 flex items-center gap-2 text-sm"><Switch checked={draft.wb.minimumTaxReserve} onCheckedChange={minimumTaxReserve=>setDraft({...draft,wb:{...draft.wb,minimumTaxReserve}})}/>Учитывать минимум УСН — 1% дохода</label><p className="mt-2 text-sm text-muted-foreground">{minimumTaxHint}</p></>}</section>
        </>}
      </fieldset>
      {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{canEdit?<Button disabled={busy||!record} onClick={()=>void save()}>{busy?"Сохраняю…":"Сохранить дефолты"}</Button>:<p className="text-sm text-muted-foreground">Общие настройки меняет владелец.</p>}
    </DialogContent>
  </Dialog>;
}
