"use client";
import { useState } from "react";
import { Container } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { NumberField } from "./candidate-workspace";
import { withSharedContainer, type CandidateContent } from "@/lib/candidate-workflow";
import { fmt } from "@/lib/market-types";

export function SharedContainer({content,onChange,disabled}:{content:CandidateContent;onChange:(c:CandidateContent)=>void;disabled?:boolean}) {
  const [open,setOpen]=useState(false);
  const value=content.sharedContainer;
  const group=value??{modelIds:[],costUsd:null,count:1,capacityM3:68,expensesRub:0};
  const resolved=withSharedContainer(content);
  return <><Button variant="outline" size="sm" disabled={disabled||content.models.length<2} onClick={()=>setOpen(true)}><Container className="size-4"/>{value?"Общий контейнер":"Объединить в контейнер"}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Общий контейнер</DialogTitle><DialogDescription>Выберите модели этого запроса, которые действительно едут вместе. Фрахт и общие расходы распределяются по объёму коробок.</DialogDescription></DialogHeader><fieldset disabled={disabled} className="space-y-4"><div className="space-y-2">{content.models.map(m=><label key={m.id} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><Checkbox checked={group.modelIds.includes(m.id)} onCheckedChange={checked=>onChange({...content,sharedContainer:{...group,modelIds:checked?[...group.modelIds,m.id]:group.modelIds.filter(id=>id!==m.id)}})}/><span className="flex-1">{m.name||"Новая модель"}</span><span className="tabular-nums text-muted-foreground">{resolved.models.find(x=>x.id===m.id)?.import.allocation?.share!=null?fmt(resolved.models.find(x=>x.id===m.id)!.import.allocation!.share!*100,1)+"%":"—"}</span></label>)}</div><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Стоимость одного контейнера, $" value={group.costUsd} onChange={costUsd=>onChange({...content,sharedContainer:{...group,costUsd}})}/><NumberField label="Контейнеров" integer value={group.count} onChange={count=>onChange({...content,sharedContainer:{...group,count:count??1}})}/><NumberField label="Полезный объём одного, м³" value={group.capacityM3} onChange={capacityM3=>onChange({...content,sharedContainer:{...group,capacityM3}})}/><NumberField label="Общие расходы всей поставки, ₽" value={group.expensesRub} onChange={expensesRub=>onChange({...content,sharedContainer:{...group,expensesRub}})}/></div><p className="text-xs leading-5 text-muted-foreground">Здесь указывайте только общие расходы. Индивидуальные расходы каждого товара остаются в его калькуляторе; одну сумму вводите один раз. Пошлина и НДС считаются отдельно по каждой модели.</p>{resolved.models.find(m=>m.import.allocation?.issue)?.import.allocation?.issue&&<p role="status" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{resolved.models.find(m=>m.import.allocation?.issue)!.import.allocation!.issue}</p>}<div className="flex justify-between gap-2"><Button variant="ghost" disabled={!value} onClick={()=>{onChange({...content,sharedContainer:null});setOpen(false);}}>Разделить поставки</Button><Button onClick={()=>setOpen(false)}>Готово</Button></div></fieldset><p className="text-xs text-muted-foreground">Изменения сохранятся кнопкой «Сохранить расчёты» в списке.</p></DialogContent></Dialog></>;
}
